FROM node:22 AS build
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build Angular application
RUN npm run build

FROM nginx:alpine
EXPOSE 80
COPY --from=build /app/dist/athenea-solutions-test /usr/share/nginx/html
# Copy nginx configuration file for route :id
COPY nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]